name: evolabs
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  # navbar 
  persistent_bottom_nav_bar_v2: ^4.2.6
  flutter_svg: ^2.0.0+1
  # sensors
  sensors_plus: ^2.0.1
  environment_sensors: ^0.1.0
  # visualizations
  fl_chart: ^0.60.0
  syncfusion_flutter_charts: ^20.4.49
  syncfusion_flutter_gauges: ^20.4.48

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
