name: Build and Create Release

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    name: Create Version Number and Release Notes
    runs-on: ubuntu-latest
    steps:
    - name: Create a timestamp for version number
      run: TZ='America/Chicago' date +%H%M%S-%m%d%y > version.txt
    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: version-date
        path: version.txt
    - uses: actions/checkout@v1
    - name: Generate release notes from git log
      run: git log -n 5 --oneline --no-merges > release.txt
    - name: Upload release.txt
      uses: actions/upload-artifact@v2
      with:
        name: release-notes
        path: release.txt

  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2.8.0
      with:
        flutter-version: '3.7.1'
    - run: cd evolabs; flutter pub get
    - run: cd evolabs; flutter build apk --release --split-per-abi
    - run: cd evolabs; flutter build appbundle
    - name: Upload apks
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: evolabs/build/app/outputs/apk/release/*.apk
    - name: Upload app-release.aab
      uses: actions/upload-artifact@v2
      with:
        name: android-aab
        path: evolabs/build/app/outputs/bundle/release/app-release.aab

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [generate-version, build-android]
    steps:
    - name: Get linux-release.tar.gz
      uses: actions/download-artifact@v2
      with:
        name: linux-release
    - name: Get apks
      uses: actions/download-artifact@v2
      with:
        name: android-apk
    - name: Get aab
      uses: actions/download-artifact@v2
      with:
        name: android-aab
    - name: Get version.txt
      uses: actions/download-artifact@v2
      with:
        name: version-date
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version.txt
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk,app-release.aab,linux-release.tar.gz"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
